apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"igor"'
  labels:
    app: spin
    app.kubernetes.io/name: igor
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.30.1
    cluster: spin-igor
  name: spin-igor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: spin-igor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        moniker.spinnaker.io/application: spin
      labels:
        app: spin
        app.kubernetes.io/name: igor
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.30.1
        cluster: spin-igor
    spec:
      affinity: {}
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=100.0
        - name: SPRING_PROFILES_ACTIVE
          value: overrides,local
        image: quay.io/opsmxpublic/ubi8-spin-igor:75231dd-10
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: igor
        ports:
        - containerPort: 8088
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sleep
            - 30d
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 650Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-igor-files-1295506707
        - mountPath: /etc/pki/ca-trust/extracted/java
          name: oes-cacerts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-igor-files-1295506707
        secret:
          defaultMode: 420
          secretName: spin-igor-files-1295506707
      - name: oes-cacerts
        secret:
          defaultMode: 420
          secretName: oes-cacerts

