apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"moniker.spinnaker.io/application":"\"spin\"","moniker.spinnaker.io/cluster":"\"igor\""},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"igor","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.30.1","cluster":"spin-igor"},"name":"spin-igor","namespace":"rahul404new"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spin","cluster":"spin-igor"}},"template":{"metadata":{"annotations":{"moniker.spinnaker.io/application":"spin"},"labels":{"app":"spin","app.kubernetes.io/managed-by":"halyard","app.kubernetes.io/name":"igor","app.kubernetes.io/part-of":"spinnaker","app.kubernetes.io/version":"1.30.1","cluster":"spin-igor"}},"spec":{"affinity":{"nodeAffinity":null,"podAffinity":null,"podAntiAffinity":null},"containers":[{"env":[{"name":"JAVA_OPTS","value":"-XX:MaxRAMPercentage=100.0"},{"name":"SPRING_PROFILES_ACTIVE","value":"overrides,local"}],"image":"quay.io/opsmxpublic/ubi8-spin-igor:75231dd-10","lifecycle":{},"livenessProbe":null,"name":"igor","ports":[{"containerPort":8088}],"readinessProbe":{"exec":{"command":["wget","--no-check-certificate","--spider","-q","http://localhost:8088/health"]},"initialDelaySeconds":null},"resources":{"limits":{},"requests":{"cpu":"100m","memory":"650Mi"}},"securityContext":null,"volumeMounts":[{"mountPath":"/opt/spinnaker/config","name":"spin-igor-files-1295506707"},{"mountPath":"/etc/pki/ca-trust/extracted/java","name":"oes-cacerts"}]}],"imagePullSecrets":[],"terminationGracePeriodSeconds":60,"tolerations":[],"volumes":[{"name":"spin-igor-files-1295506707","secret":{"secretName":"spin-igor-files-1295506707"}},{"name":"oes-cacerts","secret":{"secretName":"oes-cacerts"}}]}}}}
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"igor"'
  creationTimestamp: "2023-10-09T14:04:43Z"
  generation: 8
  labels:
    app: spin
    app.kubernetes.io/managed-by: halyard
    app.kubernetes.io/name: igor
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.30.1
    cluster: spin-igor
  name: spin-igor
  namespace: rahul404new
  resourceVersion: "632947373"
  uid: 90f74219-237c-4d54-97da-1403bc6af092
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-igor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        moniker.spinnaker.io/application: spin
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: igor
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.30.1
        cluster: spin-igor
    spec:
      affinity: {}
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=100.0
        - name: SPRING_PROFILES_ACTIVE
          value: overrides,local
        image: quay.io/opsmxpublic/ubi8-spin-igor:75231dd-10
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: igor
        ports:
        - containerPort: 8088
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8088/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 650Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-igor-files-1295506707
        - mountPath: /etc/pki/ca-trust/extracted/java
          name: oes-cacerts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-igor-files-1295506707
        secret:
          defaultMode: 420
          secretName: spin-igor-files-1295506707
      - name: oes-cacerts
        secret:
          defaultMode: 420
          secretName: oes-cacerts
status:
  conditions:
  - lastTransitionTime: "2023-10-09T14:04:43Z"
    lastUpdateTime: "2023-10-09T14:08:03Z"
    message: ReplicaSet "spin-igor-8589666fc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-12-20T03:46:42Z"
    lastUpdateTime: "2023-12-20T03:46:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
