apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"rosco"'
  labels:
    app: spin
    app.kubernetes.io/name: rosco
    app.kubernetes.io/part-of: spinnaker
    app.kubernetes.io/version: 1.30.1
    cluster: spin-rosco
  name: spin-rosco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: spin-rosco
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        moniker.spinnaker.io/application: spin
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: rosco
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.30.1
        cluster: spin-rosco
    spec:
      affinity: {}
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0
        - name: SPRING_PROFILES_ACTIVE
          value: overrides,local
        image: quay.io/opsmxpublic/ubi8-rosco-cve:1.30.120230818
        command: ["slepp","infinity"]
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        name: rosco
        ports:
        - containerPort: 8087
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8087/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-rosco-files-764606252
        - mountPath: /opt/rosco/config/packer
          name: spin-rosco-files-1045425083
        - mountPath: /opt/rosco/config/packer/scripts
          name: spin-rosco-files-442774875
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: spin-rosco-files-442774875
        secret:
          defaultMode: 420
          secretName: spin-rosco-files-442774875
      - name: spin-rosco-files-1045425083
        secret:
          defaultMode: 420
          secretName: spin-rosco-files-1045425083
      - name: spin-rosco-files-764606252
        secret:
          defaultMode: 420
          secretName: spin-rosco-files-764606252
